# Generated by Django 6.0.3 on 2026-03-18 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthropometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('body_mass_index', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('muscle_percentage', models.FloatField(blank=True, null=True)),
                ('metabolic_age', models.IntegerField(blank=True, null=True)),
                ('visceral_fat', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hip', models.FloatField(blank=True, null=True)),
                ('arm_circumference', models.FloatField(blank=True, null=True)),
                ('bicipital_skinfold', models.FloatField(blank=True, null=True)),
                ('tricipital_skinfold', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anthropometries', to='patients.patient')),
            ],
        ),
    ]
