# Generated by Django 6.0.3 on 2026-03-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_nutritionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='goal',
            field=models.CharField(choices=[('deficit', 'Déficit'), ('maintain', 'Mantenimiento'), ('superavit', 'Superávit')], max_length=20),
        ),
    ]
