# Generated by Django 6.0.3 on 2026-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_nutritionplan_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='activity_factor',
            field=models.FloatField(choices=[(1.2, 'Sedentario'), (1.375, 'Ligera actividad'), (1.55, 'Moderada actividad'), (1.725, 'Alta actividad'), (1.9, 'Muy alta actividad')]),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=10),
        ),
    ]
