# Generated by Django 6.0.3 on 2026-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pathology',
            field=models.CharField(choices=[('none', 'Ninguna'), ('diabetes', 'Diabetes'), ('hypertension', 'Hipertensión'), ('cancer', 'Cáncer'), ('malnutrition', 'Desnutrición'), ('anemia', 'Anemia'), ('muscle_gain', 'Aumento de masa muscular'), ('dyslipidemia', 'Dislipidemia'), ('gastritis', 'Gastritis'), ('colitis', 'Colitis')], default='none', max_length=30),
        ),
    ]
