# Generated by Django 6.0.3 on 2026-05-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_pathology'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlanMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(max_length=50)),
                ('item_text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='patients.nutritionplan')),
            ],
        ),
    ]
