# Generated by Django 6.0.3 on 2026-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_nutritionplanmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pathology',
        ),
        migrations.AddField(
            model_name='patient',
            name='pathologies',
            field=models.ManyToManyField(blank=True, to='patients.pathology'),
        ),
    ]
