# Generated by Django 6.0.3 on 2026-05-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_pathology_remove_patient_pathology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_reason', models.TextField(blank=True, null=True)),
                ('family_diabetes', models.BooleanField(default=False)),
                ('family_obesity', models.BooleanField(default=False)),
                ('family_cancer', models.BooleanField(default=False)),
                ('family_hypertension', models.BooleanField(default=False)),
                ('family_thyroid', models.BooleanField(default=False)),
                ('family_other', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_conditions', models.TextField(blank=True, null=True)),
                ('current_condition', models.TextField(blank=True, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('supplements', models.TextField(blank=True, null=True)),
                ('appetite', models.CharField(blank=True, choices=[('good', 'Bueno'), ('normal', 'Normal'), ('low', 'Poco')], max_length=20, null=True)),
                ('meals_per_day', models.IntegerField(blank=True, null=True)),
                ('regular_schedule', models.BooleanField(default=False)),
                ('avoided_foods', models.TextField(blank=True, null=True)),
                ('avoided_foods_reason', models.TextField(blank=True, null=True)),
                ('food_allergies', models.TextField(blank=True, null=True)),
                ('smokes', models.BooleanField(default=False)),
                ('smoking_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('drinks_alcohol', models.BooleanField(default=False)),
                ('alcohol_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('recall_breakfast', models.TextField(blank=True, null=True)),
                ('recall_morning_snack', models.TextField(blank=True, null=True)),
                ('recall_lunch', models.TextField(blank=True, null=True)),
                ('recall_afternoon_snack', models.TextField(blank=True, null=True)),
                ('recall_dinner', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_history', to='patients.patient')),
            ],
        ),
    ]
