# Generated by Django 6.0.3 on 2026-05-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_nutritionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiochemicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test_name', models.CharField(max_length=150)),
                ('result', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biochemical_tests', to='patients.patient')),
            ],
        ),
    ]
