# Generated by Django 6.0.3 on 2026-05-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_biochemicaltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('evolution', models.TextField(blank=True, null=True)),
                ('adherence', models.CharField(blank=True, max_length=50, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('plan_changes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_notes', to='patients.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_notes', to='patients.patient')),
            ],
        ),
    ]
