# Generated by Django 6.0.3 on 2026-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_followupnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplanmenuitem',
            name='option_number',
            field=models.IntegerField(default=1),
        ),
    ]
