# Generated by Django 6.0.3 on 2026-05-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_nutritionplanmenuitem_option_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplanmenuitem',
            name='active_menu_option',
            field=models.IntegerField(default=1),
        ),
    ]
