# Generated by Django 6.0.3 on 2026-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_nutritionplanmenuitem_active_menu_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('first_time', 'Primera vez'), ('follow_up', 'Seguimiento'), ('control', 'Control')], default='follow_up', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
